// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsNKTQ-6CTup7tIauCPwpoQtyYKrLouoA',
    appId: '1:83916402003:web:a6fe6311aa76675dd4c5a6',
    messagingSenderId: '83916402003',
    projectId: 'payment-bd10c',
    authDomain: 'payment-bd10c.firebaseapp.com',
    databaseURL: 'https://payment-bd10c-default-rtdb.firebaseio.com',
    storageBucket: 'payment-bd10c.appspot.com',
    measurementId: 'G-XLX8XD1PCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCza60mgHS68j-ofjQpgCYFw-D6HHLKzeg',
    appId: '1:83916402003:android:272f18998c31b66cd4c5a6',
    messagingSenderId: '83916402003',
    projectId: 'payment-bd10c',
    databaseURL: 'https://payment-bd10c-default-rtdb.firebaseio.com',
    storageBucket: 'payment-bd10c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6DxkznENJpu5tiTm923UDrajj8j5AEGA',
    appId: '1:83916402003:ios:4cfa8e0a285a1f2fd4c5a6',
    messagingSenderId: '83916402003',
    projectId: 'payment-bd10c',
    databaseURL: 'https://payment-bd10c-default-rtdb.firebaseio.com',
    storageBucket: 'payment-bd10c.appspot.com',
    iosClientId: '83916402003-etq0egl0f09bokqqtp847jvucpqaohnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.payment',
  );
}
